export const OWNER_ROLE_CODE = 'owner';
export const ADMIN_ROLE_CODE = 'admin';
export const OPERADOR_ROLE_CODE = 'operador';

export const RBAC_PERMISSION_CODES = [
  'PERFIL_LEER',
  'PERMISOS_LEER',
  'ROLES_LEER',
  'ROLES_CREAR',
  'ROLES_EDITAR',
  'ROLES_ELIMINAR',
  'USUARIOS_LEER',
  'USUARIOS_CREAR',
  'USUARIOS_EDITAR',
  'USUARIOS_CAMBIAR_ROL',
  'USUARIOS_ELIMINAR',
  // Animales
  'ANIMALES_LEER',
  'ANIMALES_CREAR',
  'ANIMALES_EDITAR',
  'ANIMALES_ELIMINAR',
  // Salud
  'SALUD_LEER',
  'SALUD_CREAR',
  'SALUD_EDITAR',
  'SALUD_ELIMINAR',
  // Reproducción
  'REPRODUCCION_LEER',
  'REPRODUCCION_CREAR',
  'REPRODUCCION_EDITAR',
  'REPRODUCCION_ELIMINAR',
  // Potreros/Lotes
  'POTREROS_LEER',
  'POTREROS_CREAR',
  'POTREROS_EDITAR',
  'POTREROS_ELIMINAR',
  // Leche
  'LECHE_LEER',
  'LECHE_CREAR',
  'LECHE_EDITAR',
  'LECHE_ELIMINAR',
  // Finanzas
  'FINANZAS_LEER',
  'FINANZAS_CREAR',
  'FINANZAS_EDITAR',
  'FINANZAS_ELIMINAR',
  // Auditorías
  'AUDITORIAS_LEER',
  'AUDITORIAS_CREAR',
  'AUDITORIAS_EDITAR',
] as const;

